Repository WildCodeSchool/2024-12-orleans-cda-project3-team-a, pull requests merged in 2025-04, with the labels that each got.

#37 Feature/variable
  packages/frontend/web/src/globals.css
Labels: Sylvain

#38 Feature/creation db
  packages/backend/migrations/src/lib/migrations/down.ts
  packages/backend/migrations/src/lib/migrations/file-migration-provider.ts
  packages/backend/migrations/src/lib/migrations/latest.ts
  packages/backend/migrations/src/lib/migrations/up.ts
  packages/backend/migrations/src/migrations/20250401122616-init-db.ts
  packages/shared/src/types/database.ts
Labels: Sylvain

#40 Feature/returnHome
  packages/frontend/web/src/components/return-home.tsx
  packages/frontend/web/src/pages/home.tsx
  packages/frontend/web/src/pages/test.tsx
  packages/frontend/web/src/router.tsx
Labels: Sylvain

#46 button-buy
  packages/frontend/web/src/components/button-buy.tsx
Labels: Sylvain

#41 Feature/close window
  packages/frontend/web/public/fonts/aerokids.otf
  packages/frontend/web/public/vite.svg
  packages/frontend/web/src/components/close-window.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/home.tsx
Labels: Sylvain

#47 Button blue
  packages/frontend/web/src/components/button-blue.tsx
Labels: Sylvain, A review🧐

#51 Feature/nb visitors moons
  packages/frontend/web/src/assets/images/icons-buttons/moon.png
  packages/frontend/web/src/components/close-window.tsx
  packages/frontend/web/src/components/info-nb-visitors-moons.tsx
  packages/frontend/web/src/components/return-home.tsx
Labels: Sylvain

#52 Feature/input
  packages/frontend/web/src/components/input-blue.tsx
  packages/frontend/web/src/pages/test.tsx
Labels: Sylvain

#55 Feature/loader
  packages/frontend/web/src/components/loader.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/test.tsx
Labels: Sylvain

#54 Feature/menu
  packages/frontend/web/src/assets/images/icons-buttons/menu.png
  packages/frontend/web/src/components/info-nb-visitors-moons.tsx
  packages/frontend/web/src/components/menu.tsx
Labels: Sylvain, A review🧐

#56 Feature/authlayout
  packages/frontend/web/src/components/auth-layout.tsx
  packages/frontend/web/src/components/bg-menu.tsx
Labels: Sylvain

#60 Feature/request game info (moon)
  packages/backend/api/src/game/get.info-park-user.ts
  packages/backend/api/src/game/index.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/src/components/button-buy.tsx
  packages/frontend/web/src/components/info-nb-visitors-moons.tsx
  packages/frontend/web/src/contexts/game-info-context.tsx
  packages/frontend/web/src/hooks/number-formatter.tsx
  packages/frontend/web/src/hooks/use-wallet.ts
  packages/frontend/web/src/main.tsx
  packages/frontend/web/src/pages/test.tsx
Labels: Sylvain, A review🧐

#67 Feature/migration
  packages/backend/migrations/src/migrations/20250425135115-table-deco.ts
  packages/shared/src/types/database.ts
Labels: Sylvain, A review🧐

#63 Feature/authentification
  .env.sample
  package-lock.json
  packages/backend/api/package.json
  packages/backend/api/src/auth/get.me.ts
  packages/backend/api/src/auth/index.ts
  packages/backend/api/src/auth/post.login.ts
  packages/backend/api/src/auth/post.logout.ts
  packages/backend/api/src/auth/post.register.ts
  packages/backend/api/src/game/get.info-park-user.ts
  packages/backend/api/src/index.ts
  packages/backend/api/src/middlewares/auth.guard.ts
  packages/backend/api/src/middlewares/auth.middlewarre.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/package.json
  packages/frontend/web/src/assets/images/icons-buttons/deconnection.png
  packages/frontend/web/src/components/button-blue.tsx
  packages/frontend/web/src/components/check-auth-layout.tsx
  packages/frontend/web/src/components/check-logged-in-layout.tsx
  packages/frontend/web/src/components/logout.tsx
  packages/frontend/web/src/components/return-home.tsx
  packages/frontend/web/src/contexts/auth-context.tsx
  packages/frontend/web/src/hooks/use-park-info.ts
  packages/frontend/web/src/hooks/use-zones-info.ts
  packages/frontend/web/src/main.tsx
  packages/frontend/web/src/pages/home.tsx
  packages/frontend/web/src/pages/login.tsx
  packages/frontend/web/src/pages/rules.tsx
  packages/frontend/web/src/pages/sign-up.tsx
  packages/frontend/web/src/pages/test.tsx
  packages/frontend/web/src/pages/welcome-layout.tsx
  packages/frontend/web/src/router.tsx
Labels: Changes requested
